import { defineChannelConnector } from './definition.js';

export default defineChannelConnector({
  id: 'gmail',
  type: 'gmail',
  name: 'Gmail',
  description:
    'Read incoming Gmail messages and send outbound email using Gmail IMAP/SMTP defaults.',
  packageName: 'imapflow + nodemailer',
  supportsReceive: true,
  supportsSend: true,
  capabilities: {
    test: true,
    send: true,
    receive: true,
    subscribe: true,
    poll: true,
    normalizeEvent: true,
    search: true,
    attachments: true,
    oauth: true,
    actions: ['test', 'send', 'poll', 'search'],
    entities: ['message', 'thread', 'attachment'],
  },
  settingsFields: [
    {
      key: 'label',
      label: 'Channel label',
      type: 'text',
      placeholder: 'gmail',
      defaultValue: 'gmail',
    },
    { key: 'enabled', label: 'Enabled', type: 'checkbox', defaultValue: true },
    {
      key: 'host',
      label: 'IMAP host',
      type: 'text',
      placeholder: 'imap.gmail.com',
      defaultValue: 'imap.gmail.com',
    },
    {
      key: 'port',
      label: 'IMAP port',
      type: 'number',
      placeholder: '993',
      defaultValue: 993,
    },
    {
      key: 'secure',
      label: 'IMAP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'username',
      label: 'Gmail address',
      type: 'text',
      placeholder: 'user@gmail.com',
      defaultValue: '',
    },
    {
      key: 'useOAuth',
      label: 'Use OAuth',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'oauthClientId',
      label: 'OAuth client ID',
      type: 'text',
      placeholder: 'Google OAuth client id',
      defaultValue: '',
    },
    {
      key: 'oauthClientSecret',
      label: 'OAuth client secret',
      type: 'password',
      placeholder: 'Google OAuth client secret',
      defaultValue: '',
    },
    {
      key: 'oauthRefreshToken',
      label: 'OAuth refresh token',
      type: 'password',
      placeholder: 'Google OAuth refresh token',
      defaultValue: '',
    },
    {
      key: 'oauthAccessToken',
      label: 'OAuth access token',
      type: 'password',
      placeholder: 'Optional cached access token',
      defaultValue: '',
    },
    {
      key: 'password',
      label: 'App password',
      type: 'password',
      placeholder: '16-character app password',
      defaultValue: '',
    },
    {
      key: 'mailbox',
      label: 'Mailbox',
      type: 'text',
      placeholder: 'INBOX',
      defaultValue: 'INBOX',
    },
    {
      key: 'smtpHost',
      label: 'SMTP host',
      type: 'text',
      placeholder: 'smtp.gmail.com',
      defaultValue: 'smtp.gmail.com',
    },
    {
      key: 'smtpPort',
      label: 'SMTP port',
      type: 'number',
      placeholder: '465',
      defaultValue: 465,
    },
    {
      key: 'smtpSecure',
      label: 'SMTP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'smtpUsername',
      label: 'SMTP username',
      type: 'text',
      placeholder: 'user@gmail.com',
      defaultValue: '',
    },
    {
      key: 'smtpPassword',
      label: 'SMTP app password',
      type: 'password',
      placeholder: '16-character app password',
      defaultValue: '',
    },
    {
      key: 'from',
      label: 'From',
      type: 'text',
      placeholder: 'user@gmail.com',
      defaultValue: '',
    },
  ],
  sendParams: ['to', 'subj', 'body', 'attachments'],
  mentioningFormulas: [
    '# /gmail summarise each incoming email in one line',
    '#7 /gmail include only payment requests and return one row per matching email',
    '/gmail:send:{"to":"user@example.com","subj":"Hi","body":"hello"}',
  ],
  help: [
    'Use /gmail in formulas to bind logic to the latest Gmail event and message payload.',
    'Use `# /gmail ...`, `#7 /gmail ...`, or `#30 /gmail ...` to process Gmail events into workbook rows.',
    'Use `/gmail:send:{"to":"user@example.com","subj":"Hi","body":"hello"}` to send outbound mail through Gmail SMTP.',
    'OAuth mode uses Google client id, client secret, and refresh token to mint access tokens for IMAP/SMTP.',
    'App-password mode is still supported when OAuth is disabled. App passwords usually require 2-Step Verification to be enabled on the Google account.',
  ],
});
