import { defineChannelConnector } from './definition.js';

export default defineChannelConnector({
  id: 'imap-email',
  type: 'imap',
  name: 'Email (IMAP + SMTP)',
  description:
    'Receive mailbox events over IMAP and send outbound mail over SMTP from the same channel.',
  packageName: 'imapflow + nodemailer',
  supportsReceive: true,
  supportsSend: true,
  settingsFields: [
    {
      key: 'label',
      label: 'Channel label',
      type: 'text',
      placeholder: 'sf',
      defaultValue: 'sf',
    },
    { key: 'enabled', label: 'Enabled', type: 'checkbox', defaultValue: true },
    {
      key: 'host',
      label: 'IMAP host',
      type: 'text',
      placeholder: 'imap.example.com',
      defaultValue: '',
    },
    {
      key: 'port',
      label: 'IMAP port',
      type: 'number',
      placeholder: '993',
      defaultValue: 993,
    },
    {
      key: 'secure',
      label: 'IMAP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'username',
      label: 'IMAP username',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
    {
      key: 'password',
      label: 'IMAP password',
      type: 'password',
      placeholder: 'App password',
      defaultValue: '',
    },
    {
      key: 'mailbox',
      label: 'Mailbox',
      type: 'text',
      placeholder: 'INBOX',
      defaultValue: 'INBOX',
    },
    {
      key: 'smtpHost',
      label: 'SMTP host',
      type: 'text',
      placeholder: 'smtp.example.com',
      defaultValue: '',
    },
    {
      key: 'smtpPort',
      label: 'SMTP port',
      type: 'number',
      placeholder: '465',
      defaultValue: 465,
    },
    {
      key: 'smtpSecure',
      label: 'SMTP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'smtpUsername',
      label: 'SMTP username',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
    {
      key: 'smtpPassword',
      label: 'SMTP password',
      type: 'password',
      placeholder: 'App password',
      defaultValue: '',
    },
    {
      key: 'from',
      label: 'From',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
  ],
  sendParams: ['to', 'subj', 'body', 'attachments'],
  mentioningFormulas: [
    '>summarize /sf in one sentence',
    '/channel1:send:message',
    '/sf:send:message',
  ],
  help: [
    'Use /sf in formulas to bind logic to the latest received email event and message payload.',
    'Use /sf:send:message with to/subj/body/attachments to send outbound mail through the same configured channel.',
  ],
});
