import { defineChannelConnector } from './definition.js';

export default defineChannelConnector({
  id: 'imap-email',
  type: 'imap',
  name: 'IMAP + SMTP',
  description:
    'Read mailbox events over IMAP and send outbound email over SMTP from the same configured mailbox.',
  packageName: 'imapflow + nodemailer',
  supportsReceive: true,
  supportsSend: true,
  capabilities: {
    test: true,
    send: true,
    receive: true,
    subscribe: true,
    poll: true,
    normalizeEvent: true,
    search: true,
    attachments: true,
    oauth: true,
    actions: ['test', 'send', 'poll', 'search'],
    entities: ['message', 'thread', 'attachment'],
  },
  settingsFields: [
    {
      key: 'label',
      label: 'Channel label',
      type: 'text',
      placeholder: 'sf',
      defaultValue: 'sf',
    },
    { key: 'enabled', label: 'Enabled', type: 'checkbox', defaultValue: true },
    {
      key: 'host',
      label: 'IMAP host',
      type: 'text',
      placeholder: 'imap.example.com',
      defaultValue: '',
    },
    {
      key: 'port',
      label: 'IMAP port',
      type: 'number',
      placeholder: '993',
      defaultValue: 993,
    },
    {
      key: 'secure',
      label: 'IMAP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'username',
      label: 'IMAP username',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
    {
      key: 'password',
      label: 'IMAP password',
      type: 'password',
      placeholder: 'App password',
      defaultValue: '',
    },
    {
      key: 'mailbox',
      label: 'Mailbox',
      type: 'text',
      placeholder: 'INBOX',
      defaultValue: 'INBOX',
    },
    {
      key: 'smtpHost',
      label: 'SMTP host',
      type: 'text',
      placeholder: 'smtp.example.com',
      defaultValue: '',
    },
    {
      key: 'smtpPort',
      label: 'SMTP port',
      type: 'number',
      placeholder: '465',
      defaultValue: 465,
    },
    {
      key: 'smtpSecure',
      label: 'SMTP secure',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      key: 'smtpUsername',
      label: 'SMTP username',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
    {
      key: 'smtpPassword',
      label: 'SMTP password',
      type: 'password',
      placeholder: 'App password',
      defaultValue: '',
    },
    {
      key: 'from',
      label: 'From',
      type: 'text',
      placeholder: 'user@example.com',
      defaultValue: '',
    },
  ],
  sendParams: ['to', 'subj', 'body', 'attachments'],
  mentioningFormulas: [
    '>summarize /sf in one sentence',
    '/sf:send:{"to":"user@example.com","subj":"Hi","body":"hello"}',
    '/sf:send:{"to":["a@example.com","b@example.com"],"subj":"Report","body":"see attached @policy"}',
  ],
  help: [
    'Use /sf in formulas to bind logic to the latest received email event and message payload.',
    'Use `/sf:send:{"to":"user@example.com","subj":"Hi","body":"hello"}` to send outbound mail through the same configured channel.',
    'Plain `/sf hello` is for channel mentions in formulas, not SMTP sends. Email sends require at least `to` and usually `subj` + `body`.',
    'If the body references workbook attachment cells, the matching files are attached to the outbound email.',
  ],
});
