import { buildFormulaHelpSection } from '../../engine/formulas/index.js';
import { buildChannelHelpSection } from '../../api/channels/connectors/index.js';

export const HELP_SECTIONS = [
  {
    title: 'Shortcuts',
    items: [
      '`Enter` commits edit',
      '`Shift+Enter` commits and moves right',
      '`Cmd/Ctrl+C` copy selection',
      '`Cmd/Ctrl+V` paste selection',
      '`Cmd/Ctrl+Z` undo committed workbook changes',
      '`Cmd/Ctrl+Shift+Z` or `Ctrl+Y` redo committed workbook changes',
      '`Cmd/Ctrl+/` toggles `Values` / `Formulas` display mode',
      '`Cmd/Ctrl+A` selects region, then full sheet on second press',
      '`Arrow keys` move active cell, `Shift+Arrow` extends selection',
      '`Report View` supports `Input:@cell` and `File:@cell` controls directly inside the report',
    ],
  },
  {
    title: 'Cell Types',
    items: [
      '`=formula` for calculations',
      "`'prompt` asks AI and shows the answer in the cell",
      '`>prompt` asks AI for a list and fills cells below',
      '`#prompt` asks AI for a table and fills cells below',
      '`/channel` picks the channel source; `\' /channel ...`, `> /channel ...`, and `# /channel ...` choose the output shape',
      '`# /channel prompt`, `#7 /channel prompt`, `#30 /channel prompt` process channel events one by one and fill one result per row below the cell',
      '`/channel` listens for incoming channel events and appends rows below with date, from, text, and file columns',
      '`File cell` stores an uploaded file, shows its filename in the sheet, and uses extracted content in formulas and AI prompts',
      '`/tg:send:hello` sends a Telegram message from a cell once on commit; bare `/tg` listens for inbound Telegram events for the configured chat',
      '`/tg` inbox rows store inbound Telegram files as real attachments, so the `file` column can open, download, and show extracted content',
      '`/channel:send:...` command cells keep a delivery log in the cell value, useful in fullscreen `Value` mode',
      '`/x:send:hello` publishes a text post to the configured Twitter/X account',
      '`/sf:send:{"to":"user@example.com","subj":"Hi","body":"hello"}` sends an email through the configured IMAP/SMTP channel',
    ],
  },
  {
    title: 'Commands',
    items: [
      '`recalc(condition, cellRef)` forces a target cell to run again when a condition becomes true. Example: `=B1>5 && recalc(B1>5, @target)`',
      '`update(cellRef, newValue)` changes another cell from a formula, useful for workflows and chained actions',
    ],
  },
  buildFormulaHelpSection(),
  buildChannelHelpSection(),
  {
    title: 'Mentioning',
    items: [
      '`A1` uses the value of cell A1 in the current sheet',
      '`Sheet 1!A1` uses the value of cell A1 from Sheet 1',
      '`A1:B5` uses the values from that region',
      '`@idea` uses the value of the cell named idea',
      '`@@idea` uses the value of the cell named idea as hidden AI context, useful for tone, instructions, or assistant persona',
      '`_@idea` uses the raw source from the cell named idea, including its formula or shortcut',
      '`!@idea` creates an internal report link to the cell named idea',
      '`@fileCell` uses the extracted content of an attached file cell, not just the filename',
      "`Input:'Sheet 1'!A1` or `Input:\"Sheet 1\"!@A1` renders a linked report input bound to a specific sheet cell",
      "`File:'Sheet 1'!D9` or `File:\"Sheet 1\"!@D9` renders a linked report file control for an uploaded or generated file cell",
      '`File:@cell:[Hint]` renders a report file picker with custom hint text before a file is selected',
      '`Input:@cell:[Placeholder]` renders a report text input with custom placeholder text',
      '`https://...` inside an AI formula fetches that URL and inserts its page content into the AI prompt',
    ],
  },
  {
    title: 'Examples',
    items: [
      "Title: AI answer in one cell\nFormula: `'Write 3 taglines for @idea`\nValue: `Smarter budgeting for every kid. | Watch savings grow in real time. | Money habits made playful.`",
      'Title: AI list spill\nFormula: `>top 10 problems that @idea solves`\nValue: `low saving motivation | poor allowance visibility | weak parent-child money conversations | delayed reward feedback ...`',
      'Title: AI table spill\nFormula: `#compare @idea with competitors;4;6`\nValue: `| Product | Strength | Weakness | Differentiator |`',
      'Title: Channel events today\nFormula: `# /sf summarise each message in one line`\nValue: `fills one generated row per today event from /sf`',
      'Title: Channel events last 7 days\nFormula: `#7 /sf extract action items`\nValue: `fills one generated row per /sf event from the last 7 days and appends new arrivals later`',
      'Title: Channel inbox log\nFormula: `/tg`\nValue: `listens for inbound Telegram events and appends one row per message with date, from, text, and file`',
      'Title: Channel inbox file\nFormula: `/tg`\nValue: `if an incoming Telegram message contains a file, the generated file cell stores the real attachment and extracted content instead of only the filename`',
      'Title: Channel AI note\nFormula: `\' /tg summarize the latest incoming event`\nValue: `returns one AI-generated note for the latest channel event in this cell`',
      'Title: Telegram send\nFormula: `/tg:send:hello from Metacells`\nValue: `sends a Telegram message once when the cell is committed`',
      'Title: Telegram send log\nFormula: `/tg:send:hello from Metacells`\nValue: `the cell value records timestamp -> sent text -> result, so fullscreen Value mode shows the send history`',
      'Title: Twitter/X send\nFormula: `/x:send:shipping update is live`\nValue: `publishes a text post through the configured Twitter/X channel`',
      'Title: Email send\nFormula: `/sf:send:{"to":"user@example.com","subj":"Hi","body":"hello"}`\nValue: `sends an email through the configured SMTP channel`',
      "Title: URL enrichment\nFormula: `'Summarise https://example.com for @idea`\nValue: `fetches the page content, inserts it into the AI prompt, and returns a summary shaped around the idea`",
      "Title: Region mention\nFormula: `'Summarise @C1:B10`\nValue: `passes the full region values into the AI prompt and returns one summary for that block`",
      'Title: Workflow update\nFormula: `=update(@target, "#new prompt;4;6")`\nValue: `rewrites the target cell so the new table prompt runs on next compute`',
      'Title: Conditional recalc\nFormula: `=B1>5 && recalc(B1>5, @target)`\nValue: `reruns the target formula only after B1 becomes greater than 5`',
      "Title: Hidden AI context\nFormula: `'Write with @@brief and @idea`\nValue: `uses the brief as hidden AI context and the idea in the visible prompt`",
      "Title: Raw source mention\nFormula: `'Audit _@A1`\nValue: `sends the raw source from A1, including its formula or shortcut, to the AI`",
      'Title: Basic report input\nFormula: `Input:@case`\nValue: `renders an editable report input bound to the @case cell`',
      'Title: Report input placeholder\nFormula: `Input:@case:[Enter your business case]`\nValue: `renders a report input with custom placeholder text and writes the typed value into @case`',
      'Title: Report file picker\nFormula: `File:@policy:[Upload policy PDF]`\nValue: `renders a report file picker with hint text; after upload it shows the filename and stores extracted content in @policy`',
      "Title: File content in AI\nFormula: `'Summarise @policy`\nValue: `if @policy is a file cell, sends the extracted file content to AI rather than the filename`",
      'Title: Telegram attachment send\nFormula: `/tg @policy uploaded`\nValue: `sends the actual attached workbook file to Telegram and uses "uploaded" as the caption/message text`',
      'Title: Inline report input\nFormula: `Enter your business case: Input:@case`\nValue: `shows a report input; typing there updates the cell named case`',
      'Title: Sheet-linked report file\nFormula: `File:\'Sheet 1\'!D9`\nValue: `renders a linked file control for D9, including generated files from =pdf(...) or =file(...)`',
      'Title: Report link\nFormula: `!@idea`\nValue: `renders a clickable report link that jumps to the idea cell`',
      'Title: Named reference formula\nFormula: `=@idea`\nValue: `pulls the current computed value from the named cell into this cell`',
      "Title: Inline AI in formula\nFormula: `='(translate @idea to German)`\nValue: `runs an inline AI call inside a formula expression and returns the translated text`",
    ],
  },
];
